import { closePool, query } from "./pool.js";

const schemaSql = `
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reputation INTEGER,
  creation_date TIMESTAMPTZ,
  display_name TEXT NOT NULL,
  last_access_date TIMESTAMPTZ,
  website_url TEXT,
  location TEXT,
  about_me TEXT,
  views INTEGER,
  upvotes INTEGER,
  downvotes INTEGER,
  profile_image_url TEXT,
  email_hash TEXT,
  account_id BIGINT
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_type_id INTEGER NOT NULL,
  accepted_answer_id BIGINT,
  parent_id BIGINT,
  creation_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deletion_date TIMESTAMPTZ,
  score INTEGER NOT NULL DEFAULT 0,
  view_count INTEGER NOT NULL DEFAULT 0,
  body TEXT NOT NULL DEFAULT '',
  owner_user_id BIGINT,
  owner_display_name TEXT,
  last_editor_user_id BIGINT,
  last_editor_display_name TEXT,
  last_edit_date TIMESTAMPTZ,
  last_activity_date TIMESTAMPTZ,
  title TEXT,
  tags TEXT,
  answer_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  favorite_count INTEGER NOT NULL DEFAULT 0,
  closed_date TIMESTAMPTZ,
  community_owned_date TIMESTAMPTZ,
  content_license TEXT DEFAULT 'CC BY-SA 4.0'
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  text TEXT NOT NULL DEFAULT '',
  creation_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_display_name TEXT,
  user_id BIGINT,
  content_license TEXT DEFAULT 'CC BY-SA 4.0'
);

CREATE TABLE IF NOT EXISTS votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  vote_type_id INTEGER NOT NULL,
  user_id BIGINT,
  creation_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  bounty_amount INTEGER
);

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_name TEXT NOT NULL UNIQUE,
  count INTEGER NOT NULL DEFAULT 0,
  excerpt_post_id BIGINT,
  wiki_post_id BIGINT,
  is_moderator_only BOOLEAN NOT NULL DEFAULT false,
  is_required BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_posts_type ON posts(post_type_id);
CREATE INDEX IF NOT EXISTS idx_posts_parent ON posts(parent_id);
CREATE INDEX IF NOT EXISTS idx_posts_score_created ON posts(score DESC, creation_date DESC);
CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(creation_date DESC);
CREATE INDEX IF NOT EXISTS idx_posts_view_count ON posts(view_count DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON comments(post_id);
CREATE INDEX IF NOT EXISTS idx_votes_post_id ON votes(post_id);
CREATE INDEX IF NOT EXISTS idx_tags_name ON tags(tag_name);
`;

async function initDb() {
  await query(schemaSql);
  console.log("Database schema initialized.");
}

initDb()
  .catch((error) => {
    console.error("Failed to initialize database schema", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closePool();
  });
