-- Run AFTER load_askubuntu.py finishes. Wires up the bits the Stack Exchange
-- dump-loader didn't need but the live backend does:
--   1. UNIQUE(tagname) so /questions tag-upsert works.
--   2. GENERATED BY DEFAULT AS IDENTITY on Id columns so /questions,
--      /answers, /comments, /upvote can INSERT without explicit IDs.
--   3. Sequence-restart values bumped past the bulk-loaded max(id).
-- Apply to BOTH clusters:
--   psql -h 127.0.0.1 -p 5434 -U madhav -d stackfast -f /path/to/post_load_alter.sql
--   psql -h 127.0.0.1 -p 5433 -U madhav -d stackfast -f /path/to/post_load_alter.sql

-- 1. tag-upsert support (idempotent).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tags_tagname_unique'
  ) THEN
    ALTER TABLE tags ADD CONSTRAINT tags_tagname_unique UNIQUE (tagname);
  END IF;
END $$;

-- 2 + 3. Promote each "id" column to identity, restart from current MAX(id)+1.
DO $$
DECLARE
  t TEXT;
  next_id BIGINT;
  is_identity TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','posts','comments','votes','badges','tags','postlinks','posthistory']
  LOOP
    SELECT a.attidentity INTO is_identity
      FROM pg_attribute a
      JOIN pg_class c ON c.oid = a.attrelid
     WHERE c.relname = t AND a.attname = 'id';

    IF is_identity = '' OR is_identity IS NULL THEN
      EXECUTE format('SELECT COALESCE(MAX(id), 0) + 1 FROM %I', t) INTO next_id;
      EXECUTE format(
        'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH %s)',
        t, next_id
      );
      RAISE NOTICE '%: identity added, restart at %', t, next_id;
    ELSE
      RAISE NOTICE '%: id is already identity (skip)', t;
    END IF;
  END LOOP;
END $$;
